/* =============================================
   GLOBE — data/solar-system.js
   Data for the Sun, all 8 planets, dwarf planets,
   and key moon data.
   ============================================= */

const SOLAR_SYSTEM = {
     sun: {
          name: "The Sun",
          emoji: "☀️",
          type: "Star (G-type Main-Sequence)",
          color: "#FFD700",
          glow: "#FF8C00",
          diameter: "1,392,700 km (109× Earth)",
          mass: "1.989 × 10³⁰ kg (333,000× Earth)",
          surface_temp: "~5,500°C (surface) · 15M°C (core)",
          distance_from_sun: "0 km (center of the Solar System)",
          orbital_period: "~225–250 million years (around Milky Way)",
          rotation_period: "~25 days (equator) · ~35 days (poles)",
          moons: 0,
          rings: false,
          age: "~4.6 billion years",
          composition: ["Hydrogen (73.46%)", "Helium (24.85%)", "Oxygen, Carbon, Neon, Iron (trace)"],
          description: "The Sun is the star at the center of our Solar System. It contains 99.86% of the total mass of the Solar System and generates energy through nuclear fusion — converting hydrogen into helium at its core, releasing enormous amounts of light and heat that make life on Earth possible.",
          fun_facts: [
               "☀️ Light from the Sun takes ~8 minutes 20 seconds to reach Earth.",
               "🔥 The Sun's corona (outer atmosphere) is paradoxically hotter (~1–3 million°C) than the surface.",
               "⚡ The Sun releases solar wind — a stream of charged particles — at 400–800 km/s.",
               "🌊 About 1.3 million Earths could fit inside the Sun.",
               "🌌 The Sun orbits the Milky Way galaxy's center once every ~225 million years (a 'cosmic year').",
               "🕳️ In ~5 billion years the Sun will expand into a Red Giant and eventually become a White Dwarf.",
          ],
          quick_stats: [
               { icon: "📏", label: "Diameter", value: "1,392,700 km" },
               { icon: "🌡️", label: "Surface Temp", value: "5,500°C" },
               { icon: "⚖️", label: "Mass", value: "333,000× Earth" },
               { icon: "⏱️", label: "Rotation", value: "~25–35 days" },
          ],
     },

     planets: [
          {
               id: "mercury",
               name: "Mercury",
               emoji: "🌑",
               order: 1,
               type: "Terrestrial / Rocky Planet",
               color: "#B5B5B5",
               glow: "#888",
               tagline: "The Fastest Planet",
               diameter: "4,879 km (0.38× Earth)",
               mass: "3.30 × 10²³ kg (0.055× Earth)",
               distance_from_sun: "57.9 million km (0.39 AU)",
               orbital_period: "87.97 Earth days",
               rotation_period: "58.65 Earth days",
               surface_temp: "-180°C to 430°C (extreme swing)",
               moons: 0,
               rings: false,
               gravity: "3.7 m/s² (0.38g)",
               atmosphere: "Extremely thin (exosphere): Oxygen, Sodium, Hydrogen, Helium",
               description: "Mercury is the smallest planet in our Solar System and the closest to the Sun. Despite being so close, it is NOT the hottest planet (that's Venus). Mercury has no atmosphere to trap heat, giving it the most extreme temperature swings of any planet — scorching hot during the day and freezing cold at night.",
               fun_facts: [
                    "🏃 Mercury orbits the Sun faster than any other planet — 88 days per year.",
                    "🌡️ Surface temperatures swing from -180°C to 430°C in a single rotation.",
                    "🕳️ Mercury's core makes up about 85% of its radius — unusually large iron core.",
                    "🌑 A day on Mercury (sunrise to sunrise) is longer than its year — ~176 Earth days.",
                    "🔭 Mercury was observed by ancient civilizations; Galileo studied it with a telescope in 1631.",
                    "🚀 Only two spacecraft have visited Mercury: Mariner 10 (1974) and MESSENGER (2011–2015).",
               ],
               quick_stats: [
                    { icon: "📏", label: "Diameter", value: "4,879 km" },
                    { icon: "🌡️", label: "Temp Range", value: "-180 to 430°C" },
                    { icon: "🌙", label: "Moons", value: "0" },
                    { icon: "⏱️", label: "Year Length", value: "88 Earth days" },
               ],
               NASA_photo_keyword: "mercury planet surface",
          },
          {
               id: "venus",
               name: "Venus",
               emoji: "🌕",
               order: 2,
               type: "Terrestrial / Rocky Planet",
               color: "#E8C56D",
               glow: "#D4A017",
               tagline: "The Hottest Planet",
               diameter: "12,104 km (0.95× Earth)",
               mass: "4.87 × 10²⁴ kg (0.815× Earth)",
               distance_from_sun: "108.2 million km (0.72 AU)",
               orbital_period: "224.7 Earth days",
               rotation_period: "243 Earth days (retrograde — spins backwards!)",
               surface_temp: "~465°C (constant, day & night)",
               moons: 0,
               rings: false,
               gravity: "8.87 m/s² (0.9g)",
               atmosphere: "Thick: 96.5% Carbon Dioxide, 3.5% Nitrogen · Sulfuric acid clouds",
               description: "Venus is often called Earth's twin due to similar size and mass, but its environment is hellish. A runaway greenhouse effect has made it the hottest planet in the Solar System with surface temperatures hot enough to melt lead. Its thick CO₂ atmosphere creates immense pressure — 92× that of Earth's. Venus also rotates backwards (retrograde) and very slowly — a day on Venus is longer than its year.",
               fun_facts: [
                    "🔥 Venus is hotter than Mercury despite being farther from the Sun — due to its greenhouse effect.",
                    "🔄 Venus rotates backwards — the Sun rises in the west and sets in the east.",
                    "☁️ Clouds on Venus are made of sulfuric acid droplets and reflect ~70% of sunlight.",
                    "⏰ A solar day on Venus lasts 117 Earth days.",
                    "🌟 Venus is the brightest natural object in the night sky after the Moon — the 'Morning Star' or 'Evening Star'.",
                    "🚀 The Soviet Venera probes landed on Venus in the 1970s–80s, surviving up to ~2 hours before being destroyed.",
               ],
               quick_stats: [
                    { icon: "📏", label: "Diameter", value: "12,104 km" },
                    { icon: "🌡️", label: "Avg Temp", value: "465°C" },
                    { icon: "🌙", label: "Moons", value: "0" },
                    { icon: "⏱️", label: "Year Length", value: "225 Earth days" },
               ],
               NASA_photo_keyword: "venus planet surface",
          },
          {
               id: "earth",
               name: "Earth",
               emoji: "🌍",
               order: 3,
               type: "Terrestrial / Rocky Planet — Our Home",
               color: "#3A8FD1",
               glow: "#2ecc71",
               tagline: "The Blue Marble — Only Known Life in the Universe",
               diameter: "12,742 km",
               mass: "5.97 × 10²⁴ kg",
               distance_from_sun: "149.6 million km (1 AU — defines the Astronomical Unit)",
               orbital_period: "365.25 days (1 year)",
               rotation_period: "23 hrs 56 min 4 sec (1 sidereal day)",
               surface_temp: "−89°C to 57°C (avg 15°C)",
               moons: 1,
               rings: false,
               gravity: "9.8 m/s² (1g)",
               atmosphere: "78% Nitrogen, 21% Oxygen, 1% Argon + trace gases",
               description: "Earth is the third planet from the Sun and the only known planet to harbor life. About 71% of Earth's surface is covered by water — earning it the name 'The Blue Marble'. Earth's magnetic field protects it from harmful solar radiation, and its moon stabilizes its axial tilt, giving us regular seasons. Earth formed ~4.5 billion years ago and life appeared ~3.8 billion years ago.",
               fun_facts: [
                    "💧 Earth is the only planet known to have liquid water on its surface.",
                    "🧲 Earth has a powerful magnetic field generated by its molten iron-nickel outer core.",
                    "🌘 The Moon formed from debris after a Mars-sized object (Theia) collided with early Earth.",
                    "🌋 Earth has 7 tectonic plates constantly moving — causing earthquakes and volcanic eruptions.",
                    "🌀 The planet's atmosphere is a thin protective layer — if Earth were a basketball, the atmosphere would be thinner than a sheet of paper.",
                    "🌱 Earth recycles carbon continuously through the carbon cycle — crucial for sustaining life.",
               ],
               quick_stats: [
                    { icon: "📏", label: "Diameter", value: "12,742 km" },
                    { icon: "🌡️", label: "Avg Temp", value: "15°C" },
                    { icon: "🌙", label: "Moons", value: "1 (The Moon)" },
                    { icon: "⏱️", label: "Year Length", value: "365.25 days" },
               ],
               NASA_photo_keyword: "earth blue marble space",
          },
          {
               id: "mars",
               name: "Mars",
               emoji: "🔴",
               order: 4,
               type: "Terrestrial / Rocky Planet",
               color: "#C1440E",
               glow: "#FF4500",
               tagline: "The Red Planet",
               diameter: "6,779 km (0.53× Earth)",
               mass: "6.39 × 10²³ kg (0.107× Earth)",
               distance_from_sun: "227.9 million km (1.52 AU)",
               orbital_period: "686.97 Earth days (~1.88 years)",
               rotation_period: "24 hrs 37 min (very similar to Earth!)",
               surface_temp: "−125°C to 20°C (avg −60°C)",
               moons: 2,
               rings: false,
               gravity: "3.72 m/s² (0.38g)",
               atmosphere: "Thin: 95% CO₂, 2.7% Nitrogen, 1.6% Argon",
               description: "Mars is the fourth planet from the Sun, often called 'The Red Planet' because of iron oxide (rust) on its surface giving it that distinctive red color. Mars has the tallest volcano in the Solar System (Olympus Mons — 22 km tall) and the longest canyon (Valles Marineris — 4,000 km long). Mars is the most studied planet besides Earth and is the prime candidate for future human colonization.",
               fun_facts: [
                    "🏔️ Olympus Mons on Mars is the largest volcano in the Solar System — nearly 3× the height of Mt. Everest.",
                    "🕳️ Valles Marineris is a canyon system stretching ~4,000 km (as long as the US is wide).",
                    "💧 Mars has water ice at its polar caps and evidence of ancient river valleys.",
                    "🌪️ Mars experiences massive dust storms that can cover the entire planet for months.",
                    "👾 Mars has two tiny moons — Phobos and Deimos — which may be captured asteroids.",
                    "🚀 Over 50 missions have been sent to Mars, including rovers: Curiosity (2012) and Perseverance (2021).",
               ],
               quick_stats: [
                    { icon: "📏", label: "Diameter", value: "6,779 km" },
                    { icon: "🌡️", label: "Avg Temp", value: "−60°C" },
                    { icon: "🌙", label: "Moons", value: "2 (Phobos & Deimos)" },
                    { icon: "⏱️", label: "Year Length", value: "687 Earth days" },
               ],
               NASA_photo_keyword: "mars planet red surface",
          },
          {
               id: "jupiter",
               name: "Jupiter",
               emoji: "🪐",
               order: 5,
               type: "Gas Giant",
               color: "#C88B3A",
               glow: "#E8A246",
               tagline: "The Largest Planet — King of the Solar System",
               diameter: "139,820 km (11× Earth)",
               mass: "1.90 × 10²⁷ kg (318× Earth)",
               distance_from_sun: "778.5 million km (5.2 AU)",
               orbital_period: "11.86 Earth years",
               rotation_period: "9 hrs 56 min (fastest rotation of any planet!)",
               surface_temp: "−108°C (cloud tops)",
               moons: 95,
               rings: true,
               gravity: "24.8 m/s² (2.53g)",
               atmosphere: "89% Hydrogen, 10% Helium + trace methane, ammonia, water",
               description: "Jupiter is the fifth planet from the Sun and by far the largest — so large that if it were hollow, more than 1,300 Earths would fit inside. Jupiter is a gas giant with no solid surface. Its most famous feature is the Great Red Spot, a storm that has raged for over 350 years. Jupiter acts as the Solar System's 'vacuum cleaner', its immense gravity capturing comets and asteroids that might otherwise head towards Earth.",
               fun_facts: [
                    "⚡ Jupiter's Great Red Spot is a storm system larger than Earth that has been raging for at least 350 years.",
                    "🔄 Jupiter rotates so fast (less than 10 hours!) that it bulges at the equator, giving it an oblate shape.",
                    "🌙 Jupiter has 95 known moons — including the 4 Galilean moons: Io, Europa, Ganymede, and Callisto.",
                    "🌊 Europa (a moon of Jupiter) has a subsurface ocean of liquid water and is considered a top candidate for extraterrestrial life.",
                    "🛡️ Jupiter's gravity acts as a shield, deflecting comets and asteroids away from the inner solar system.",
                    "🚀 Pioneer 10 was the first spacecraft to fly past Jupiter in 1973; Juno spacecraft is currently in orbit (since 2016).",
               ],
               quick_stats: [
                    { icon: "📏", label: "Diameter", value: "139,820 km" },
                    { icon: "🌡️", label: "Cloud Temp", value: "−108°C" },
                    { icon: "🌙", label: "Moons", value: "95 known" },
                    { icon: "⏱️", label: "Year Length", value: "11.86 Earth years" },
               ],
               NASA_photo_keyword: "jupiter great red spot planet",
          },
          {
               id: "saturn",
               name: "Saturn",
               emoji: "🪐",
               order: 6,
               type: "Gas Giant",
               color: "#E4D191",
               glow: "#C9B454",
               tagline: "The Ringed Beauty",
               diameter: "116,460 km (9.14× Earth)",
               mass: "5.68 × 10²⁶ kg (95.16× Earth)",
               distance_from_sun: "1.43 billion km (9.58 AU)",
               orbital_period: "29.46 Earth years",
               rotation_period: "10 hrs 33 min",
               surface_temp: "−178°C (cloud tops)",
               moons: 146,
               rings: true,
               gravity: "10.44 m/s² (1.07g)",
               atmosphere: "96.3% Hydrogen, 3.25% Helium + trace methane, ammonia, water",
               description: "Saturn is the sixth planet from the Sun and the second largest. It is most famous for its stunning ring system — made up of billions of pieces of ice and rock ranging from tiny grains to chunks as large as a house. Saturn is the least dense planet in the Solar System — it would float on water! It has 146 known moons, including Titan — the only moon with a thick atmosphere — and Enceladus, which has geysers of water ice erupting from its south pole.",
               fun_facts: [
                    "💍 Saturn's rings span about 282,000 km but are surprisingly thin — only about 10 to 1,000 meters thick.",
                    "🏊 Saturn is the only planet less dense than water (density: 0.687 g/cm³) — it would float in a giant bathtub!",
                    "🌙 Titan (Saturn's moon) has a thick nitrogen atmosphere and lakes of liquid methane — unique in the Solar System.",
                    "❄️ Enceladus shoots giant geysers of water ice into space — likely has a liquid water ocean beneath its icy crust.",
                    "⬡ Saturn has a mysterious hexagonal storm pattern at its north pole with sides larger than Earth.",
                    "🚀 Cassini–Huygens spacecraft orbited Saturn from 2004 to 2017, sending back extraordinary data and images.",
               ],
               quick_stats: [
                    { icon: "📏", label: "Diameter", value: "116,460 km" },
                    { icon: "🌡️", label: "Cloud Temp", value: "−178°C" },
                    { icon: "🌙", label: "Moons", value: "146 known" },
                    { icon: "⏱️", label: "Year Length", value: "29.46 Earth years" },
               ],
               NASA_photo_keyword: "saturn rings planet cassini",
          },
          {
               id: "uranus",
               name: "Uranus",
               emoji: "🔵",
               order: 7,
               type: "Ice Giant",
               color: "#7DE8E8",
               glow: "#4BC5D4",
               tagline: "The Sideways Planet",
               diameter: "50,724 km (4× Earth)",
               mass: "8.68 × 10²⁵ kg (14.54× Earth)",
               distance_from_sun: "2.87 billion km (19.2 AU)",
               orbital_period: "84.01 Earth years",
               rotation_period: "17 hrs 14 min (retrograde)",
               surface_temp: "−224°C (coldest planetary atmosphere)",
               moons: 28,
               rings: true,
               gravity: "8.87 m/s² (0.89g)",
               atmosphere: "83% Hydrogen, 15% Helium, 2.3% Methane (gives its blue-green color)",
               description: "Uranus is the seventh planet from the Sun and one of two 'ice giants' (along with Neptune). Its most defining feature is that it rotates on its side — with an axial tilt of 97.77°, likely caused by a massive collision early in its history. This means Uranus experiences extreme seasons, with each pole getting about 42 years of continuous sunlight followed by 42 years of darkness. Its blue-green color comes from methane in its atmosphere absorbing red light.",
               fun_facts: [
                    "↔️ Uranus orbits the Sun essentially rolling on its side — its axial tilt is 97.8°.",
                    "🥶 Uranus has the coldest atmosphere of any planet — reaching −224°C.",
                    "💍 Uranus has 13 known rings, discovered in 1977 — they are dark and narrow unlike Saturn's.",
                    "🌙 All 28 moons of Uranus are named after characters from Shakespeare and Alexander Pope's works.",
                    "🔭 Uranus was the first planet discovered with a telescope, by William Herschel in 1781.",
                    "🌪️ Despite being an 'ice giant', the 'ice' is actually a hot, dense fluid of water, methane, and ammonia — not ice.",
               ],
               quick_stats: [
                    { icon: "📏", label: "Diameter", value: "50,724 km" },
                    { icon: "🌡️", label: "Min Temp", value: "−224°C" },
                    { icon: "🌙", label: "Moons", value: "28 known" },
                    { icon: "⏱️", label: "Year Length", value: "84 Earth years" },
               ],
               NASA_photo_keyword: "uranus planet blue ice giant",
          },
          {
               id: "neptune",
               name: "Neptune",
               emoji: "🌀",
               order: 8,
               type: "Ice Giant",
               color: "#4169E1",
               glow: "#1E90FF",
               tagline: "The Windiest Planet",
               diameter: "49,244 km (3.88× Earth)",
               mass: "1.02 × 10²⁶ kg (17.15× Earth)",
               distance_from_sun: "4.5 billion km (30.07 AU)",
               orbital_period: "164.8 Earth years",
               rotation_period: "16 hrs 6 min",
               surface_temp: "−214°C (avg)",
               moons: 16,
               rings: true,
               gravity: "11.15 m/s² (1.14g)",
               atmosphere: "80% Hydrogen, 19% Helium, 1.5% Methane",
               description: "Neptune is the eighth and farthest planet from the Sun. It is a deep blue ice giant with the strongest winds in the Solar System — reaching speeds of over 2,100 km/h (faster than the speed of sound). Neptune has a large storm system called the Great Dark Spot, similar to Jupiter's Great Red Spot. Due to its extreme distance, Neptune takes nearly 165 Earth years to complete one orbit — meaning it has only completed one full orbit since its discovery in 1846.",
               fun_facts: [
                    "💨 Neptune has the strongest winds of any planet — over 2,100 km/h (faster than sound on Earth!).",
                    "🔮 Neptune's largest moon, Triton, orbits backwards (retrograde) — it was likely captured from the Kuiper Belt.",
                    "❄️ Triton has geysers of liquid nitrogen erupting from its surface.",
                    "🔭 Neptune was the first planet predicted mathematically before it was directly observed (1846).",
                    "🌊 Neptune emits more heat than it receives from the Sun — it has an internal heat source.",
                    "🚀 Only Voyager 2 has ever visited Neptune, doing a flyby in 1989.",
               ],
               quick_stats: [
                    { icon: "📏", label: "Diameter", value: "49,244 km" },
                    { icon: "🌡️", label: "Avg Temp", value: "−214°C" },
                    { icon: "🌙", label: "Moons", value: "16 known" },
                    { icon: "⏱️", label: "Year Length", value: "164.8 Earth years" },
               ],
               NASA_photo_keyword: "neptune planet deep blue ice",
          },
     ],

     dwarf_planets: [
          {
               id: "pluto",
               name: "Pluto",
               emoji: "⚫",
               color: "#C9A882",
               tagline: "The Beloved Dwarf",
               type: "Dwarf Planet (Kuiper Belt Object)",
               diameter: "2,377 km (0.19× Earth)",
               distance_from_sun: "5.9 billion km (39.5 AU)",
               orbital_period: "248 Earth years",
               moons: 5,
               description: "Pluto was considered the 9th planet from 1930 until 2006, when the International Astronomical Union (IAU) reclassified it as a 'dwarf planet'. It lies in the Kuiper Belt beyond Neptune. Despite its small size, Pluto has 5 moons, with Charon being so large relative to Pluto that the two are considered a double dwarf planet system. NASA's New Horizons spacecraft flew past Pluto in 2015, revealing a heart-shaped nitrogen ice plain (Tombaugh Regio) and surprisingly complex geology.",
               fun_facts: [
                    "💔 Pluto was demoted from 'planet' to 'dwarf planet' by the IAU in 2006.",
                    "❤️ Pluto has a giant heart-shaped glacier of nitrogen ice — Tombaugh Regio.",
                    "🌙 Charon (Pluto's largest moon) is half the size of Pluto — they orbit their common center of mass.",
                    "🥶 Surface temperature: -233°C — one of the coldest places in the Solar System.",
                    "🔭 Pluto was discovered in 1930 by 24-year-old Clyde Tombaugh.",
               ],
          },
          {
               id: "eris",
               name: "Eris",
               emoji: "⚫",
               color: "#D3D3D3",
               tagline: "The Troublemaker",
               type: "Dwarf Planet (Scattered Disc Object)",
               diameter: "2,326 km (similar to Pluto)",
               distance_from_sun: "~10 billion km (68 AU average)",
               orbital_period: "559 Earth years",
               moons: 1,
               description: "Eris is one of the most massive known dwarf planets in our Solar System. Its discovery in 2005 directly triggered the reclassification of Pluto — because if Pluto was a planet, so was Eris. Named after the Greek goddess of discord, Eris appropriately caused great discord in the astronomy world. It lies in the scattered disc region beyond the Kuiper Belt.",
               fun_facts: [
                    "🏆 Eris is sometimes called the '10th planet' — its discovery led to Pluto's reclassification.",
                    "🥶 At ~10 billion km from the Sun, Eris receives very little sunlight — surface temp is about -243°C.",
                    "🌙 Eris has one moon — Dysnomia (named after the daughter of Eris, the goddess of lawlessness).",
                    "⚖️ Eris is slightly smaller than Pluto in diameter but has a higher mass.",
               ],
          },
          {
               id: "ceres",
               name: "Ceres",
               emoji: "⚫",
               color: "#A9A9A9",
               tagline: "The Asteroid Belt's Giant",
               type: "Dwarf Planet (Asteroid Belt)",
               diameter: "939 km",
               distance_from_sun: "~414 million km (2.77 AU)",
               orbital_period: "4.6 Earth years",
               moons: 0,
               description: "Ceres is the only dwarf planet in the inner Solar System, located in the asteroid belt between Mars and Jupiter. It was the first asteroid ever discovered (1801) and later reclassified as a dwarf planet in 2006. Despite its small size, Ceres contains about 1/3 of the total mass of the entire asteroid belt. NASA's Dawn spacecraft orbited Ceres in 2015, revealing mysterious bright spots in a crater (Occator) — later confirmed to be salt deposits from briny water that once flowed to the surface.",
               fun_facts: [
                    "💧 Ceres has water ice beneath its surface and may have a thin water vapor atmosphere.",
                    "✨ Mysterious bright spots in Occator Crater are salt deposits from ancient brine water.",
                    "🔭 Ceres was the first object discovered in the asteroid belt, by Giuseppe Piazzi in 1801.",
                    "⚖️ Ceres contains ~1/3 of the total mass of the entire asteroid belt.",
               ],
          },
          {
               id: "makemake",
               name: "Makemake",
               emoji: "⚫",
               color: "#B87333",
               tagline: "The Kuiper Belt's Red World",
               type: "Dwarf Planet (Kuiper Belt)",
               diameter: "~1,430 km",
               distance_from_sun: "~6.8 billion km (45.8 AU)",
               orbital_period: "309.9 Earth years",
               moons: 1,
               description: "Makemake is the second-brightest Kuiper Belt object after Pluto, and one of the largest dwarf planets. It is covered in frozen methane and has a reddish-brown color. Named after the creator god of the Rapa Nui people of Easter Island. It has one known moon, discovered in 2016.",
               fun_facts: [
                    "🔴 Makemake has a distinctive reddish color due to frozen methane on its surface.",
                    "🔭 Makemake was discovered in 2005, right after Easter — originally nicknamed 'Easterbunny' by its discoverers.",
                    "🌙 Its moon (nicknamed MK2) was discovered in 2016 using the Hubble Space Telescope.",
               ],
          },
          {
               id: "haumea",
               name: "Haumea",
               emoji: "⚫",
               color: "#F0F0F0",
               tagline: "The Spinning Oval",
               type: "Dwarf Planet (Kuiper Belt)",
               diameter: "1,960 × 1,518 × 996 km (elongated shape)",
               distance_from_sun: "~6.47 billion km (43.3 AU)",
               orbital_period: "285 Earth years",
               moons: 2,
               description: "Haumea is one of the fastest-spinning large objects in the Solar System, completing a rotation in just under 4 hours. This rapid spin has stretched it into an elongated 'rugby ball' shape. It has a ring system discovered in 2017 — only the third non-giant planet known to have rings. It has two moons: Hi'iaka and Namaka.",
               fun_facts: [
                    "🏈 Haumea spins so fast (once every 3.9 hours) that centrifugal force has squashed it into an elongated egg shape.",
                    "💍 Haumea is one of very few non-giant planets known to have a ring system.",
                    "🌙 It has two moons: Hi'iaka and Namaka, named after Hawaiian goddesses.",
                    "🔭 Haumea was discovered in 2004 by Mike Brown's team at Caltech.",
               ],
          },
     ],

     key_facts: [
          { icon: "📏", label: "Solar System Age", value: "~4.6 Billion Years" },
          { icon: "🌑", label: "Total Planets", value: "8 Official Planets" },
          { icon: "⚫", label: "Dwarf Planets", value: "5 Recognized" },
          { icon: "🌙", label: "Total Moons", value: "290+ Known" },
          { icon: "☄️", label: "Asteroid Belt", value: "Between Mars & Jupiter" },
          { icon: "🛸", label: "Kuiper Belt", value: "Beyond Neptune's Orbit" },
          { icon: "☀️", label: "Star Type", value: "G-type Yellow Dwarf" },
          { icon: "🌌", label: "Nearest Star", value: "Proxima Centauri (4.2 ly)" },
     ],
};
